#Tarea Final

##Ingesta de datos

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('TrainingSetValues.csv')

### Analisis de Variables

In [2]:
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [3]:
#Para ver si hay algún pozo duplicado:
print(df['id'].duplicated().sum())

0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  str
 3   funder                 55763 non-null  str
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  str
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59398 non-null  str
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  str
 11  subvillage             59029 non-null  str
 12  region                 59400 non-null  str
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  str
 16  ward                   59400 non-null  str
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  str
 20  scheme_management      55522 non-null  str
 21  scheme_name            30590 non-null  str
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  str
 25  extraction_type_group  59400 non-null  str
 26  extraction_type_class  59400 non-null  str
 27  management             59400 non-null  str
 28  management_group       59400 non-null  str
 29  payment                59400 non-null  str
 30  payment_type           59400 non-null  str
 31  water_quality          59400 non-null  str
 32  quality_group          59400 non-null  str
 33  quantity               59400 non-null  str
 34  quantity_group         59400 non-null  str
 35  source                 59400 non-null  str
 36  source_type            59400 non-null  str
 37  source_class           59400 non-null  str
 38  waterpoint_type        59400 non-null  str
 39  waterpoint_type_group  59400 non-null  str
dtypes: float64(3), int64(7), object(2), str(28)
memory usage: 32.2+ MB

Columnas con +30% de los valores nulos: scheme_name

### Variables numericas

In [5]:
df.describe()

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
count,59400.000000,59400.000000,59400.000000,59400.000000,5.940000e+04,59400.000000,59400.000000,59400.000000,59400.000000,59400.000000
mean,37115.131768,317.650385,668.297239,34.077427,-5.706033e+00,0.474141,15.297003,5.629747,179.909983,1300.652475
std,21453.128371,2997.574558,693.116350,6.567432,2.946019e+00,12.236230,17.587406,9.633649,471.482176,951.620547
min,0.000000,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,1.000000,0.000000,0.000000,0.000000
25%,18519.750000,0.000000,0.000000,33.090347,-8.540621e+00,0.000000,5.000000,2.000000,0.000000,0.000000
50%,37061.500000,0.000000,369.000000,34.908743,-5.021597e+00,0.000000,12.000000,3.000000,25.000000,1986.000000
75%,55656.500000,20.000000,1319.250000,37.178387,-3.326156e+00,0.000000,17.000000,5.000000,215.000000,2004.000000
max,74247.000000,350000.000000,2770.000000,40.345193,-2.000000e-08,1776.000000,99.000000,80.000000,30500.000000,2013.000000

Hay columnas con minimo 0 que pintan outlier: num_private, construction_year, district_code.
Pero el amount_tsh se dispara el máximo en comparación con el 75%. Vamos a ver los percentiles

In [6]:
df.describe(percentiles= [0.25, 0.5, 0.75, 0.9, 0.95,0.99])

,id,amount_tsh,gps_height,longitude,latitude,num_private,region_code,district_code,population,construction_year
count,59400.000000,59400.000000,59400.000000,59400.000000,5.940000e+04,59400.000000,59400.000000,59400.000000,59400.000000,59400.000000
mean,37115.131768,317.650385,668.297239,34.077427,-5.706033e+00,0.474141,15.297003,5.629747,179.909983,1300.652475
std,21453.128371,2997.574558,693.116350,6.567432,2.946019e+00,12.236230,17.587406,9.633649,471.482176,951.620547
min,0.000000,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,1.000000,0.000000,0.000000,0.000000
25%,18519.750000,0.000000,0.000000,33.090347,-8.540621e+00,0.000000,5.000000,2.000000,0.000000,0.000000
50%,37061.500000,0.000000,369.000000,34.908743,-5.021597e+00,0.000000,12.000000,3.000000,25.000000,1986.000000
75%,55656.500000,20.000000,1319.250000,37.178387,-3.326156e+00,0.000000,17.000000,5.000000,215.000000,2004.000000
90%,66863.100000,500.000000,1638.000000,38.780334,-2.101167e+00,0.000000,20.000000,7.000000,453.000000,2009.000000
95%,70564.050000,1200.000000,1797.000000,39.133240,-1.408872e+00,0.000000,60.000000,30.000000,680.000000,2010.000000
99%,73518.010000,5000.000000,2142.000000,39.768406,-2.000000e-08,5.000000,90.000000,53.000000,2000.000000,2012.000000
max,74247.000000,350000.000000,2770.000000,40.345193,-2.000000e-08,1776.000000,99.000000,80.000000,30500.000000,2013.000000

Efectivamente en amount_tsh del 99% al máximo hay mucha distancia, al igual que en num_private pero es no creo que sirva para el modelo

### Variables categóricas

In [7]:
for i in df.columns:
    print(i)
    print(df[i].value_counts())

id
id
69572    1
8776     1
34310    1
67743    1
19728    1
        ..
60739    1
27263    1
37057    1
31282    1
26348    1
Name: count, Length: 59400, dtype: int64
amount_tsh
amount_tsh
0.00        41639
500.00       3102
50.00        2472
1000.00      1488
20.00        1463
            ...
38000.00        1
0.25            1
12.00           1
60000.00        1
59.00           1
Name: count, Length: 98, dtype: int64
date_recorded
date_recorded
2011-03-15    572
2011-03-17    558
2013-02-03    546
2011-03-14    520
2011-03-16    513
             ...
2011-09-25      1
2004-04-01      1
2011-09-26      1
2011-09-12      1
2013-12-01      1
Name: count, Length: 356, dtype: int64
funder
funder
Government Of Tanzania    9084
Danida                    3114
Hesawa                    2202
Rwssp                     1374
World Bank                1349
                          ...
Cida                         1
Dwe/anglican Church          1
Dina                         1
Brown                        1
Samlo                        1
Name: count, Length: 1896, dtype: int64
gps_height
gps_height
 0       20438
-15         60
-16         55
-13         55
-20         52
         ...
 2072        1
 2209        1
-90          1
 2091        1
 2366        1
Name: count, Length: 2428, dtype: int64
installer
installer
DWE                    17402
Government              1825
RWE                     1206
Commu                   1060
DANIDA                  1050
                       ...
DWE/Anglican church        1
VIFAI                      1
Dina                       1
brown                      1
SELEPTA                    1
Name: count, Length: 2145, dtype: int64
longitude
longitude
0.000000     1812
33.015597       2
39.090880       2
37.339811       2
32.988560       2
             ...
37.169807       1
35.249991       1
34.017087       1
35.861315       1
38.104048       1
Name: count, Length: 57516, dtype: int64
latitude
latitude
-2.000000e-08    1812
-2.487085e+00       2
-6.981830e+00       2
-7.065373e+00       2
-2.489378e+00       2
                 ...
-3.253847e+00       1
-9.070629e+00       1
-8.750434e+00       1
-6.378573e+00       1
-6.747464e+00       1
Name: count, Length: 57517, dtype: int64
wpt_name
wpt_name
none                   3563
Shuleni                1748
Zahanati                830
Msikitini               535
Kanisani                323
                       ...
Chimeredya                1
Area Three Namba 27       1
Kwa Yahona Kuvala         1
Mshoro                    1
Kwa Mzee Lugawa           1
Name: count, Length: 37399, dtype: int64
num_private
num_private
0       58643
6          81
1          73
5          46
8          46
        ...
60          1
111         1
300         1
55          1
1402        1
Name: count, Length: 65, dtype: int64
basin
basin
Lake Victoria              10248
Pangani                     8940
Rufiji                      7976
Internal                    7785
Lake Tanganyika             6432
Wami / Ruvu                 5987
Lake Nyasa                  5085
Ruvuma / Southern Coast     4493
Lake Rukwa                  2454
Name: count, dtype: int64
subvillage
subvillage
Madukani        508
Shuleni         506
Majengo         502
Kati            373
Mtakuja         262
               ...
Hu                1
Nduza             1
Itete B           1
Maore Kati        1
Kikatanyemba      1
Name: count, Length: 19287, dtype: int64
region
region
Iringa           5294
Shinyanga        4982
Mbeya            4639
Kilimanjaro      4379
Morogoro         4006
Arusha           3350
Kagera           3316
Mwanza           3102
Kigoma           2816
Ruvuma           2640
Pwani            2635
Tanga            2547
Dodoma           2201
Singida          2093
Mara             1969
Tabora           1959
Rukwa            1808
Mtwara           1730
Manyara          1583
Lindi            1546
Dar es Salaam     805
Name: count, dtype: int64
region_code
region_code
11    5300
17    5011
12    4639
3     4379
5     4040
18    3324
19    3047
2     3024
16    2816
10    2640
4     2513
1     2201
13    2093
14    1979
20    1969
15    1808
6     1609
21    1583
80    1238
60    1025
90     917
7      805
99     423
9      390
24     326
8      300
40       1
Name: count, dtype: int64
district_code
district_code
1     12203
2     11173
3      9998
4      8999
5      4356
6      4074
7      3343
8      1043
30      995
33      874
53      745
43      505
13      391
23      293
63      195
62      109
60       63
0        23
80       12
67        6
Name: count, dtype: int64
lga
lga
Njombe          2503
Arusha Rural    1252
Moshi Rural     1251
Bariadi         1177
Rungwe          1106
                ...
Moshi Urban       79
Kigoma Urban      71
Arusha Urban      63
Lindi Urban       21
Nyamagana          1
Name: count, Length: 125, dtype: int64
ward
ward
Igosi        307
Imalinyi     252
Siha Kati    232
Mdandu       231
Nduruma      217
            ...
Mlimani        1
Korongoni      1
Chinugulu      1
Nyamtinga      1
Kinungu        1
Name: count, Length: 2092, dtype: int64
population
population
0       21381
1        7025
200      1940
150      1892
250      1681
        ...
2569        1
541         1
845         1
976         1
788         1
Name: count, Length: 1049, dtype: int64
public_meeting
public_meeting
True     51011
False     5055
Name: count, dtype: int64
recorded_by
recorded_by
GeoData Consultants Ltd    59400
Name: count, dtype: int64
scheme_management
scheme_management
VWC                 36793
WUG                  5206
Water authority      3153
WUA                  2883
Water Board          2748
Parastatal           1680
Private operator     1063
Company              1061
Other                 766
SWC                    97
Trust                  72
Name: count, dtype: int64
scheme_name
scheme_name
K                       682
Borehole                546
Chalinze wate           405
M                       400
DANIDA                  379
                       ...
Upper RUVU                1
TWESA                     1
BL Nsherehehe             1
Magati  gravity spri      1
Mtawanya                  1
Name: count, Length: 2695, dtype: int64
permit
permit
True     38852
False    17492
Name: count, dtype: int64
construction_year
construction_year
0       20709
2010     2645
2008     2613
2009     2533
2000     2091
2007     1587
2006     1471
2003     1286
2011     1256
2004     1123
2012     1084
2002     1075
1978     1037
1995     1014
2005     1011
1999      979
1998      966
1990      954
1985      945
1980      811
1996      811
1984      779
1982      744
1994      738
1972      708
1974      676
1997      644
1992      640
1993      608
2001      540
1988      521
1983      488
1975      437
1986      434
1976      414
1970      411
1991      324
1989      316
1987      302
1981      238
1977      202
1979      192
1973      184
2013      176
1971      145
1960      102
1967       88
1963       85
1968       77
1969       59
1964       40
1962       30
1961       21
1965       19
1966       17
Name: count, dtype: int64
extraction_type
extraction_type
gravity                      26780
nira/tanira                   8154
other                         6430
submersible                   4764
swn 80                        3670
mono                          2865
india mark ii                 2400
afridev                       1770
ksb                           1415
other - rope pump              451
other - swn 81                 229
windmill                       117
india mark iii                  98
cemo                            90
other - play pump               85
walimi                          48
climax                          32
other - mkulima/shinyanga        2
Name: count, dtype: int64
extraction_type_group
extraction_type_group
gravity            26780
nira/tanira         8154
other               6430
submersible         6179
swn 80              3670
mono                2865
india mark ii       2400
afridev             1770
rope pump            451
other handpump       364
other motorpump      122
wind-powered         117
india mark iii        98
Name: count, dtype: int64
extraction_type_class
extraction_type_class
gravity         26780
handpump        16456
other            6430
submersible      6179
motorpump        2987
rope pump         451
wind-powered      117
Name: count, dtype: int64
management
management
vwc                 40507
wug                  6515
water board          2933
wua                  2535
private operator     1971
parastatal           1768
water authority       904
other                 844
company               685
unknown               561
other - school         99
trust                  78
Name: count, dtype: int64
management_group
management_group
user-group    52490
commercial     3638
parastatal     1768
other           943
unknown         561
Name: count, dtype: int64
payment
payment
never pay                25348
pay per bucket            8985
pay monthly               8300
unknown                   8157
pay when scheme fails     3914
pay annually              3642
other                     1054
Name: count, dtype: int64
payment_type
payment_type
never pay     25348
per bucket     8985
monthly        8300
unknown        8157
on failure     3914
annually       3642
other          1054
Name: count, dtype: int64
water_quality
water_quality
soft                  50818
salty                  4856
unknown                1876
milky                   804
coloured                490
salty abandoned         339
fluoride                200
fluoride abandoned       17
Name: count, dtype: int64
quality_group
quality_group
good        50818
salty        5195
unknown      1876
milky         804
colored       490
fluoride      217
Name: count, dtype: int64
quantity
quantity
enough          33186
insufficient    15129
dry              6246
seasonal         4050
unknown           789
Name: count, dtype: int64
quantity_group
quantity_group
enough          33186
insufficient    15129
dry              6246
seasonal         4050
unknown           789
Name: count, dtype: int64
source
source
spring                  17021
shallow well            16824
machine dbh             11075
river                    9612
rainwater harvesting     2295
hand dtw                  874
lake                      765
dam                       656
other                     212
unknown                    66
Name: count, dtype: int64
source_type
source_type
spring                  17021
shallow well            16824
borehole                11949
river/lake              10377
rainwater harvesting     2295
dam                       656
other                     278
Name: count, dtype: int64
source_class
source_class
groundwater    45794
surface        13328
unknown          278
Name: count, dtype: int64
waterpoint_type
waterpoint_type
communal standpipe             28522
hand pump                      17488
other                           6380
communal standpipe multiple     6103
improved spring                  784
cattle trough                    116
dam                                7
Name: count, dtype: int64
waterpoint_type_group
waterpoint_type_group
communal standpipe    34625
hand pump             17488
other                  6380
improved spring         784
cattle trough           116
dam                       7
Name: count, dtype: int64

Categoricas repetidas: payment_type(mismo todo payment)quantity_group(mismo quantity)

In [8]:
print(df.nunique())

id                       59400
amount_tsh                  98
date_recorded              356
funder                    1896
gps_height                2428
installer                 2145
longitude                57516
latitude                 57517
wpt_name                 37399
num_private                 65
basin                        9
subvillage               19287
region                      21
region_code                 27
district_code               20
lga                        125
ward                      2092
population                1049
public_meeting               2
recorded_by                  1
scheme_management           11
scheme_name               2695
permit                       2
construction_year           55
extraction_type             18
extraction_type_group       13
extraction_type_class        7
management                  12
management_group             5
payment                      7
payment_type                 7
water_quality                8
quality_group                6
quantity                     5
quantity_group               5
source                      10
source_type                  7
source_class                 3
waterpoint_type              7
waterpoint_type_group        6
dtype: int64

# Limpieza de datos

## Acción en variables categóricas
### Razón de las columnas eliminadas:
### No aportan valor predictivo:
**id**: Es únicamente un identificador numérico de fila.

**recorded_by**: Solo tiene 1 único valor para todos los pozos del dataset ("GeoData Consultants Ltd").

**scheme_name**: Contiene casi un 50% de valores nulos y altísima cardinalidad (2.695 nombres diferentes). Aporta demasiado ruido y rellenar esa cantidad de nulos sería inventarse la mitad de la información.

**subvillage**: Decidimos borrar la columna por completo debido a su extrema cardinalidad (19.287 pueblos distintos). Aporta demasiado ruido geográfico y ya tenemos la ubicación cubierta con la latitud/longitud y la región.

### Limpieza por repetidas o mejor explicadas:

**extraction_type** (18 valores) y **extraction_type_group** (13 valores): Aportan la misma información sobre el método de extracción pero con demasiado detalle. Se eliminan en favor de extraction_type_class, que resume lo mismo en solo 7 categorías perfectas para el modelo.

**region_code** y **district_code**: Son códigos numéricos redundantes de la ubicación geográfica. Al ser números, el modelo puede interpretarlos erróneamente como valores continuos (creyendo que la región 20 "vale más" que la 10). La ubicación ya está bien cubierta con la columna de texto region y las coordenadas.

**management** Esta más resumido en la columna management_group 

**payment_type**: Es un duplicado exacto de la columna payment (ambas tienen los mismos 7 valores).

**water_quality**: Tiene demasiadas categorías pequeñas con muy pocos datos (ej. "fluoride abandoned" con solo 17 filas), lo que provoca sobreajuste. Se elimina en favor de quality_group, que agrupa estos detalles en bloques más representativos.

**quantity_group**: Es otro duplicado matemáticamente exacto de la columna quantity (ambas distribuyen la información en las mismas 5 categorías).

**source** (10 valores) y **source_class** (3 valores): Son redundantes. source tiene demasiado nivel de detalle (categorías con menos de 50 registros) y source_class es demasiado genérica. Se eliminan para quedarse con la opción intermedia y más equilibrada: source_type.

**waterpoint_type**: Es prácticamente idéntica a waterpoint_type_group, pero esta última agrupa de forma más limpia las categorías minoritarias, reduciendo el número de columnas a la hora de hacer el One-Hot Encoding.

## Columnas con nulos:
**subvillage (371 nulos)**: Eliminar. Aunque tiene muy pocos nulos, decidimos borrar la columna por completo debido a su extrema cardinalidad (19.287 pueblos distintos). Aporta demasiado ruido geográfico y ya tenemos la ubicación cubierta con la latitud/longitud y la región.

**funder (3.637 nulos)** e **installer (3.655 nulos)**: Imputar con 'Desconocido'. Al ser variables de texto con muchísimos valores, los algoritmos fallarían si dejamos los vacíos.

**scheme_management (3.878 nulos)**: Imputar con 'Other'. Es una variable de baja cardinalidad (solo 11 valores) que convenientemente ya incluye la categoría "Other" (Otros). Aprovechamos esta categoría existente para absorber los valores faltantes de una forma muy limpia para el negocio.

**public_meeting (3.334 nulos)** y **permit (3.056 nulos)**: Imputar con la Moda (True). Ambas son variables booleanas (Verdadero o Falso). Al observar los datos, la inmensa mayoría de los pozos sí tienen reuniones públicas y sí tienen permiso. Por estadística básica, aplicamos la moda y asumimos que los que no tienen el dato registrado probablemente también sean True.

In [9]:
def limpiar_datos_cat(df):

    df_clean = df.copy()
    
    # 1. Eliminar columnas inútiles
    cols_drop = ['id', 'subvillage', 'recorded_by', 'scheme_name', 'extraction_type', 'extraction_type_group', 'region_code', 'district_code',
                 'management', 'payment_type', 'water_quality', 'quantity_group', 'source_class', 'source', 'waterpoint_type' ]
    df_clean = df_clean.drop(columns=cols_drop)
    
    # 2. Imputar nulos
    # Textos de alta cardinalidad: Rellenar con 'unknown'
    df_clean['funder'] = df_clean['funder'].fillna('Unknown')
    df_clean['installer'] = df_clean['installer'].fillna('Unknown')
    df_clean['scheme_management'] = df_clean['scheme_management'].fillna('Other')
    df_clean['public_meeting'] = df_clean['public_meeting'].fillna(True)
    df_clean['permit'] = df_clean['permit'].fillna(True)
    
    # Texto de baja cardinalidad: Lo metemos en la categoría 'Other' que ya existe
    df_clean['scheme_management'] = df_clean['scheme_management'].fillna('Other')
    
    # Booleanos: Rellenar con el valor más probable (La moda: True)
    df_clean['public_meeting'] = df_clean['public_meeting'].fillna(True)
    df_clean['permit'] = df_clean['permit'].fillna(True)


    
    return df_clean

In [10]:
df_fase1 = limpiar_datos_cat(df)
df_fase1.head(10)

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,...,scheme_management,permit,construction_year,extraction_type_class,management_group,payment,quality_group,quantity,source_type,waterpoint_type_group
0,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,...,VWC,False,1999,gravity,user-group,pay annually,good,enough,spring,communal standpipe
1,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,...,Other,True,2010,gravity,user-group,never pay,good,insufficient,rainwater harvesting,communal standpipe
2,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,...,VWC,True,2009,gravity,user-group,pay per bucket,good,enough,dam,communal standpipe
3,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,...,VWC,True,1986,submersible,user-group,never pay,good,dry,borehole,communal standpipe
4,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,...,Other,True,0,gravity,other,never pay,good,seasonal,rainwater harvesting,communal standpipe
5,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587,Tajiri,0,Pangani,...,VWC,True,2009,submersible,user-group,pay per bucket,salty,enough,other,communal standpipe
6,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365,Kwa Ngomho,0,Internal,...,VWC,True,0,handpump,user-group,never pay,good,enough,borehole,hand pump
7,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198,Tushirikiane,0,Lake Tanganyika,...,Other,True,0,handpump,user-group,unknown,milky,enough,shallow well,hand pump
8,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712,Kwa Ramadhan Musa,0,Lake Tanganyika,...,VWC,True,0,handpump,user-group,never pay,salty,seasonal,borehole,hand pump
9,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051,Kwapeto,0,Lake Victoria,...,Other,True,0,handpump,user-group,never pay,good,enough,shallow well,hand pump

In [11]:
df_fase1.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   amount_tsh             59400 non-null  float64
 1   date_recorded          59400 non-null  str
 2   funder                 59400 non-null  str
 3   gps_height             59400 non-null  int64
 4   installer              59400 non-null  str
 5   longitude              59400 non-null  float64
 6   latitude               59400 non-null  float64
 7   wpt_name               59398 non-null  str
 8   num_private            59400 non-null  int64
 9   basin                  59400 non-null  str
 10  region                 59400 non-null  str
 11  lga                    59400 non-null  str
 12  ward                   59400 non-null  str
 13  population             59400 non-null  int64
 14  public_meeting         59400 non-null  object
 15  scheme_management      59400 non-null  str
 16  permit                 59400 non-null  object
 17  construction_year      59400 non-null  int64
 18  extraction_type_class  59400 non-null  str
 19  management_group       59400 non-null  str
 20  payment                59400 non-null  str
 21  quality_group          59400 non-null  str
 22  quantity               59400 non-null  str
 23  source_type            59400 non-null  str
 24  waterpoint_type_group  59400 non-null  str
dtypes: float64(3), int64(4), object(2), str(16)
memory usage: 19.1+ MB

Poner Dtypes de la mejor manera posible

outliers y Falsos Ceros

In [12]:
df_fase1.describe(percentiles= [0.25, 0.5, 0.75, 0.9, 0.95,0.99])

,amount_tsh,gps_height,longitude,latitude,num_private,population,construction_year
count,59400.000000,59400.000000,59400.000000,5.940000e+04,59400.000000,59400.000000,59400.000000
mean,317.650385,668.297239,34.077427,-5.706033e+00,0.474141,179.909983,1300.652475
std,2997.574558,693.116350,6.567432,2.946019e+00,12.236230,471.482176,951.620547
min,0.000000,-90.000000,0.000000,-1.164944e+01,0.000000,0.000000,0.000000
25%,0.000000,0.000000,33.090347,-8.540621e+00,0.000000,0.000000,0.000000
50%,0.000000,369.000000,34.908743,-5.021597e+00,0.000000,25.000000,1986.000000
75%,20.000000,1319.250000,37.178387,-3.326156e+00,0.000000,215.000000,2004.000000
90%,500.000000,1638.000000,38.780334,-2.101167e+00,0.000000,453.000000,2009.000000
95%,1200.000000,1797.000000,39.133240,-1.408872e+00,0.000000,680.000000,2010.000000
99%,5000.000000,2142.000000,39.768406,-2.000000e-08,5.000000,2000.000000,2012.000000
max,350000.000000,2770.000000,40.345193,-2.000000e-08,1776.000000,30500.000000,2013.000000

**amount_tsh**: Al ser el más del 95%:0 y el máximo:669, lo mejor es eliminarlo

In [13]:
df_fase1['amount_tsh'].describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])

count     59400.000000
mean        317.650385
std        2997.574558
min           0.000000
25%           0.000000
50%           0.000000
75%          20.000000
90%         500.000000
95%        1200.000000
99%        5000.000000
max      350000.000000
Name: amount_tsh, dtype: float64

Más de la mitad del recuento es 0, puede ser por falta de agua o por error. Al no saberlo bien se puede hacer una columna binaria para indicar si tiene presión o no.

**population**

Para ver si la población mínima y del 25% es 0, vamos a ver las coordenadas y ver si hay casas cerca.

In [14]:
pozos_pob_cero = df_fase1[df_fase1['population'] == 0][['longitude', 'latitude', 'population']]
display(pozos_pob_cero.head(15))
len(pozos_pob_cero)

    longitude      latitude  population
4   31.130847 -1.825359e+00           0
6   33.362410 -3.766365e+00           0
7   32.620617 -4.226198e+00           0
8   32.711100 -5.146712e+00           0
9   30.626991 -1.257051e+00           0
12  33.798106 -3.290194e+00           0
14  34.364073 -3.629333e+00           0
21   0.000000 -2.000000e-08           0
27  31.104257 -1.735361e+00           0
30  36.108312 -5.791000e+00           0
36  33.854345 -9.638520e+00           0
37  35.858373 -4.647906e+00           0
41  33.927902 -9.204649e+00           0
45  33.345260 -3.838998e+00           0
47  33.540607 -9.172905e+00           0

21381

-1.257051, 30.626991: hay población cerca
-9.172905, 33.540607: hay población cerca
-4.647906, 35.858373: hay población cerca
Al ser el 36% vemos como está formado el resto para después poder tomar una decisión:

In [15]:
df_fase1['population'].describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])

count    59400.000000
mean       179.909983
std        471.482176
min          0.000000
25%          0.000000
50%         25.000000
75%        215.000000
90%        453.000000
95%        680.000000
99%       2000.000000
max      30500.000000
Name: population, dtype: float64

In [16]:
#Population más grande para ver donde se ubica:
pozos_pob_cero = df_fase1[df_fase1['population'] == 30500][['longitude', 'latitude', 'population']]
pozos_pob_cero

       longitude  latitude  population
30537  38.783756 -5.181904       30500

El pozo con más "Population" se ubica en Kwebwewe una ciudad con una población según city-fast de 128.901 habitantes.

Al haber un alto porcentaje de 0 junto a una gran diferencia entre la media(179) y la mediana (25) debido a poblados con mucha población. Para sustituir estos 0 es necesario basarse en alguna variable que pueda determinar que población aproximada hay cerca, teniendo como opción la ubicación. Vamos a mirar las regiones la media y mediana que tienen, siendo posible tomarlo como referencia para asignar.

In [17]:
stats_poblacion = df_fase1[df_fase1['population'] > 0].groupby('region')['population'].agg(['mean', 'median', 'count', 'std', 'max', 'min'])


stats_poblacion = stats_poblacion.sort_values(by='median', ascending=False)

print(stats_poblacion)

                     mean  median  count         std    max  min
region
Shinyanga      428.359756   500.0    164  224.024946   1500    1
Mwanza         552.070845   400.0    367  493.794049   5000    1
Kigoma         505.810054   360.0   2785  590.972462   8500    1
Mara           538.794312   300.0   1969  831.300180  10000    1
Lindi          364.404916   300.0   1546  400.230048   5050    1
Manyara        317.778269   213.0   1583  582.243701  15300    1
Rukwa          375.558773   200.0   1761  750.746680  10000    1
Morogoro       264.625562   200.0   4006  336.062820   5000    1
Singida        279.389287   200.0   2091  494.377984   9000    1
Arusha         262.317408   150.0   3349  442.733646   9500    1
Dar es Salaam  240.843478   150.0    805  534.198421   9865    1
Mtwara         267.441618   123.0   1730  443.022905   5016    1
Ruvuma         241.790612   100.0   2173  483.515680   8000    1
Tanga          246.753828    80.0   2547  790.250035  30500    1
Iringa         120.883051    54.0   4130  207.994290   3072    1
Pwani          349.618831    50.0   2634  970.509564  11463    1
Kilimanjaro    105.747888    40.0   4379  294.260177   8000    1

In [18]:
stats_poblacion = df_fase1[df_fase1['population'] == 0].groupby('region')['population'].agg([ 'count'])

stats_poblacion = stats_poblacion.sort_values(by='count', ascending=False)

print(stats_poblacion)

           count
region
Shinyanga   4818
Mbeya       4639
Kagera      3316
Mwanza      2735
Dodoma      2201
Tabora      1959
Iringa      1164
Ruvuma       467
Rukwa         47
Kigoma        31
Singida        2
Arusha         1
Pwani          1

En regiones como Shinyanga, hay 1.258 pozos con la población en 0 frente a solo 53 con datos reales; por lo tanto, sería peligroso generalizar a partir de una muestra tan pequeña

Viendo que las medianas no están en proporción con los máximos la mejor manera de sustituir los 0 de la mejor manera posible es según la region a la que pertenece

**longitude y latitude**

Tambien mirar que longitudes o latitudes están mal. Para ello se utiliza los valores que pueden estar fuera de rango siendo cercanos al 0. Primero vemos los cercano al 0 y después los que están fuera de Tanzania.

In [19]:
## Cercanos a 0:
if 'longitude' in df_fase1.columns and 'latitude' in df_fase1.columns:
        # a) Marcar como nulos los "falsos ceros"
        df_fase1['longitude'] = df_fase1['longitude'].replace(0.0, pd.NA)
        df_fase1['latitude'] = df_fase1['latitude'].replace(0.0, pd.NA)
    
df_fase1[['longitude', 'latitude']].info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   longitude  57588 non-null  object
 1   latitude   59400 non-null  float64
dtypes: float64(1), object(1)
memory usage: 928.3+ KB

In [20]:
#Ahora los que está fuera de Tarzania
# Límites aproximados: Longitud [29.0, 41.0], Latitud [-12.0, 0.0]
if 'longitude' in df_fase1.columns and 'latitude' in df_fase1.columns:
        df_fase1['longitude'] = df_fase1['longitude'].where((df_fase1['longitude'] >= 29.0) & (df_fase1['longitude'] <= 41.0), pd.NA)
        df_fase1['latitude'] = df_fase1['latitude'].where((df_fase1['latitude'] >= -12.0) & (df_fase1['latitude'] <= 0.0), pd.NA)

df_fase1[['longitude', 'latitude']].info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   longitude  57588 non-null  object
 1   latitude   59400 non-null  float64
dtypes: float64(1), object(1)
memory usage: 928.3+ KB

Se han visto afectadas 1.812 Latitudes afectadas pero por estar a 0, habiendo pasado las demás por el filtro de los límites aproximados de Tanzania. Para sustituir los pocos nulos se va a poner la media de la región para poder poner la ubicación dentro de la región

**construction_year**:

Al igual que con la población es mejor verlo por regiones y poder ver si se puede cambiar los 0 por la media o mediana de la región

In [21]:
stats_construction = df_fase1[df_fase1['construction_year'] > 0].groupby('region')['construction_year'].agg(['mean', 'median', 'count', 'std', 'max', 'min'])

stats_construction = stats_construction.sort_values(by='median', ascending=False)

print(stats_construction)

                      mean  median  count        std   max   min
region
Pwani          2002.857666  2007.0   2459   9.986162  2011  1964
Shinyanga      2002.621951  2005.0    164   5.762456  2012  1985
Manyara        2002.114013  2004.0   1570   9.803441  2013  1964
Kilimanjaro    1996.543278  2002.0   4344  14.748032  2013  1960
Arusha         1998.808427  2001.0   3299  11.915853  2013  1960
Kigoma         1998.029223  2001.0   2806  10.822891  2013  1966
Singida        1994.338129  2000.0   2085  13.520203  2012  1960
Dar es Salaam  2001.040609  2000.0    788  11.041489  2010  1960
Iringa         1997.441284  2000.0   4922  11.488838  2011  1964
Mara           1997.454918  1998.0   1952  11.537118  2012  1960
Lindi          1994.842289  1997.0   1433  13.656049  2013  1960
Morogoro       1996.025326  1997.0   3988  11.629409  2011  1960
Ruvuma         1997.446265  1997.0   2624  10.002448  2013  1968
Mwanza         1994.050704  1996.0    355  11.245977  2011  1963
Tanga          1992.623318  1996.0   2453  14.658288  2011  1960
Rukwa          1989.858804  1988.0   1806  10.459128  2012  1965
Mtwara         1992.373707  1988.0   1643  13.297554  2013  1966

La mejor opción es cambiar los 0 por la mediana de las regiones, pero vamos a ver el conteo de las que tienen como año de construcción 0.

In [22]:
stats_construction = df_fase1[df_fase1['construction_year'] == 0].groupby('region')['construction_year'].agg([ 'count'])

stats_construction = stats_poblacion.sort_values(by='count', ascending=False)

print(stats_construction)

           count
region
Shinyanga   4818
Mbeya       4639
Kagera      3316
Mwanza      2735
Dodoma      2201
Tabora      1959
Iringa      1164
Ruvuma       467
Rukwa         47
Kigoma        31
Singida        2
Arusha         1
Pwani          1

En regiones como Shinyanga, hay 4.818 pozos con el año de construcción en 0 frente a solo 164 con datos reales, Igual que en la población.

# Acciones Variables Numéricas
## Valores intactos:
**amount_tsh**: 
**gps_height** Min: -90. Puede ser posible que esté a la altura por debajo del mar, por lo tanto se deja.

## Valores anómalos:
**longitude y latitude**:  Se vuelve aplicar los filtros anteriores para cuando se tenga que meter información nueva.

**construction_year** y **population**: Min: 0, 25%: 0. Tienen exactamente el mismo patrón de datos faltantes sistemáticos (regiones enteras como Mbeya o Kagera registran exclusivamente ceros). Para evitar sesgos por muestras pequeñas, se aplica una **imputación híbrida**: se usa la mediana de la región solo si esta cuenta con un mínimo histórico fiable (> 150 registros válidos); en caso contrario, se imputa la mediana global.

## Columnas añadidas:
**has_amount_tsh**: Menciona si tiene presión medida o no.


## Columnas eliminadas:
**num_private**: No aporta valor.

In [23]:
def limpiar_datos_num(df):

    df_clean = df.copy()
    umbral_confianza = 150
    
    #Creación de tablas
    df_clean['has_amount_tsh'] = (df_clean['amount_tsh'] > 0).astype(int)
    df_clean['has_construction_year'] = (df_clean['construction_year'] > 0).astype(int)
    df_clean['has_population'] = (df_clean['population'] > 0).astype(int)
    
    #Pasar los 0 a nulos y de nulos a lo mencionado anteriomente
    #construction_year
    df_clean['construction_year'] = df_clean['construction_year'].replace(0, np.nan)
    conteos_year = df_clean.groupby('region')['construction_year'].count()
    regiones_fiables_year = conteos_year[conteos_year >= umbral_confianza].index
    
    falta_year = df_clean['construction_year'].isna()
    es_fiable_year = df_clean['region'].isin(regiones_fiables_year)
    
    df_clean.loc[falta_year & es_fiable_year, 'construction_year'] = df_clean.groupby('region')['construction_year'].transform('median')
    df_clean.loc[falta_year & ~es_fiable_year, 'construction_year'] = df_clean['construction_year'].median()
    #Population

    df_clean['population'] = df_clean['population'].replace(0, np.nan)
    conteos_pop = df_clean.groupby('region')['population'].count()
    regiones_fiables_pop = conteos_pop[conteos_pop >= umbral_confianza].index
    
    falta_pop = df_clean['population'].isna()
    es_fiable_pop = df_clean['region'].isin(regiones_fiables_pop)
    
    df_clean.loc[falta_pop & es_fiable_pop, 'population'] = df_clean.groupby('region')['population'].transform('median')
    df_clean.loc[falta_pop & ~es_fiable_pop, 'population'] = df_clean['population'].median()
    

    # Latitud y Longitud: Reemplazar, aplicar media
    
    df_clean['longitude'] = pd.to_numeric(df_clean['longitude'], errors='coerce')
    df_clean['latitude'] = pd.to_numeric(df_clean['latitude'], errors='coerce')

    df_clean['longitude'] = df_clean['longitude'].replace(0.0, np.nan)
    df_clean['latitude'] = df_clean['latitude'].replace(0.0, np.nan)

    df_clean['longitude'] = df_clean['longitude'].fillna(df_clean.groupby('region')['longitude'].transform('median'))
    df_clean['latitude'] = df_clean['latitude'].fillna(df_clean.groupby('region')['latitude'].transform('median'))

    df_clean['longitude'] = df_clean['longitude'].fillna(df_clean['longitude'].median())
    df_clean['latitude'] = df_clean['latitude'].fillna(df_clean['latitude'].median())
    
    #Añadimos columna:
    df_clean['has_amount_tsh'] = (df_clean['amount_tsh'] > 0).astype(int)

    #Eliminamos columna:
    df_clean = df_clean.drop(columns=['num_private'])

    return df_clean

In [24]:
df_fase2 = limpiar_datos_num(df_fase1)
df_fase2.head(15)

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,basin,region,...,extraction_type_class,management_group,payment,quality_group,quantity,source_type,waterpoint_type_group,has_amount_tsh,has_construction_year,has_population
0,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,Lake Nyasa,Iringa,...,gravity,user-group,pay annually,good,enough,spring,communal standpipe,1,1,1
1,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,Lake Victoria,Mara,...,gravity,user-group,never pay,good,insufficient,rainwater harvesting,communal standpipe,0,1,1
2,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,Pangani,Manyara,...,gravity,user-group,pay per bucket,good,enough,dam,communal standpipe,1,1,1
3,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,Ruvuma / Southern Coast,Mtwara,...,submersible,user-group,never pay,good,dry,borehole,communal standpipe,0,1,1
4,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,Lake Victoria,Kagera,...,gravity,other,never pay,good,seasonal,rainwater harvesting,communal standpipe,0,0,0
5,20.0,2011-03-13,Mkinga Distric Coun,0,DWE,39.172796,-4.765587,Tajiri,Pangani,Tanga,...,submersible,user-group,pay per bucket,salty,enough,other,communal standpipe,1,1,1
6,0.0,2012-10-01,Dwsp,0,DWSP,33.362410,-3.766365,Kwa Ngomho,Internal,Shinyanga,...,handpump,user-group,never pay,good,enough,borehole,hand pump,0,0,0
7,0.0,2012-10-09,Rwssp,0,DWE,32.620617,-4.226198,Tushirikiane,Lake Tanganyika,Shinyanga,...,handpump,user-group,unknown,milky,enough,shallow well,hand pump,0,0,0
8,0.0,2012-11-03,Wateraid,0,Water Aid,32.711100,-5.146712,Kwa Ramadhan Musa,Lake Tanganyika,Tabora,...,handpump,user-group,never pay,salty,seasonal,borehole,hand pump,0,0,0
9,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051,Kwapeto,Lake Victoria,Kagera,...,handpump,user-group,never pay,good,enough,shallow well,hand pump,0,0,0
10,0.0,2011-02-20,Private,62,Private,39.209518,-7.034139,Mzee Hokororo,Wami / Ruvu,Pwani,...,submersible,commercial,never pay,salty,enough,borehole,other,0,1,1
11,200.0,2013-02-18,Danida,1062,DANIDA,35.770258,-10.574175,Kwa Alid Nchimbi,Lake Nyasa,Ruvuma,...,handpump,user-group,pay when scheme fails,good,insufficient,shallow well,hand pump,1,1,1
12,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194,Pamba,Internal,Shinyanga,...,handpump,user-group,other,good,enough,shallow well,hand pump,0,0,0
13,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783,Kwa John Izack Mmari,Pangani,Kilimanjaro,...,gravity,user-group,pay monthly,good,enough,spring,communal standpipe,0,1,1
14,0.0,2012-10-20,Biore,0,WEDECO,34.364073,-3.629333,Mwabasabi,Internal,Shinyanga,...,handpump,user-group,never pay,good,enough,shallow well,hand pump,0,0,0

In [25]:
df_fase2.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   amount_tsh             59400 non-null  float64
 1   date_recorded          59400 non-null  str
 2   funder                 59400 non-null  str
 3   gps_height             59400 non-null  int64
 4   installer              59400 non-null  str
 5   longitude              59400 non-null  float64
 6   latitude               59400 non-null  float64
 7   wpt_name               59398 non-null  str
 8   basin                  59400 non-null  str
 9   region                 59400 non-null  str
 10  lga                    59400 non-null  str
 11  ward                   59400 non-null  str
 12  population             59400 non-null  float64
 13  public_meeting         59400 non-null  object
 14  scheme_management      59400 non-null  str
 15  permit                 59400 non-null  object
 16  construction_year      59400 non-null  float64
 17  extraction_type_class  59400 non-null  str
 18  management_group       59400 non-null  str
 19  payment                59400 non-null  str
 20  quality_group          59400 non-null  str
 21  quantity               59400 non-null  str
 22  source_type            59400 non-null  str
 23  waterpoint_type_group  59400 non-null  str
 24  has_amount_tsh         59400 non-null  int64
 25  has_construction_year  59400 non-null  int64
 26  has_population         59400 non-null  int64
dtypes: float64(5), int64(4), object(2), str(16)
memory usage: 20.0+ MB

# Cardinalidad

In [26]:
df_fase2.nunique()

amount_tsh                  98
date_recorded              356
funder                    1896
gps_height                2428
installer                 2145
longitude                57515
latitude                 57517
wpt_name                 37399
basin                        9
region                      21
lga                        125
ward                      2092
population                1048
public_meeting               2
scheme_management           11
permit                       2
construction_year           54
extraction_type_class        7
management_group             5
payment                      7
quality_group                6
quantity                     5
source_type                  7
waterpoint_type_group        6
has_amount_tsh               2
has_construction_year        2
has_population               2
dtype: int64

### Funder

In [27]:
print(df_fase2['funder'].value_counts().to_string())

funder
Government Of Tanzania            9084
Unknown                           3641
Danida                            3114
Hesawa                            2202
Rwssp                             1374
World Bank                        1349
Kkkt                              1287
World Vision                      1246
Unicef                            1057
Tasaf                              877
District Council                   843
Dhv                                829
Private Individual                 826
Dwsp                               811
0                                  777
Norad                              765
Germany Republi                    610
Tcrs                               602
Ministry Of Water                  590
Water                              583
Dwe                                484
Netherlands                        470
Hifab                              450
Adb                                448
Lga                                442
Amref                              425
Fini Water                         393
Oxfam                              359
Wateraid                           333
Rc Church                          321
Isf                                316
Rudep                              312
Mission                            301
Private                            295
Jaica                              280
Roman                              275
Rural Water Supply And Sanitat     270
Adra                               263
Ces(gmbh)                          260
Jica                               259
Shipo                              241
Wsdp                               234
Rc                                 230
Finw                               219
Dh                                 213
Ded                                198
Plan Int                           195
Kiliwater                          189
Dmdd                               186
Go                                 181
Lawatefuka Water Supply            180
Oxfarm                             176
Magadini-makiwaru Water            175
Fw                                 173
W.B                                170
Kkkt_makwale                       166
Ces (gmbh)                         165
Wvt                                158
Oikos E.Afrika                     155
Nethalan                           152
Mkinga Distric Coun                150
Lvia                               147
Concern World Wide                 145
Unhcr                              137
No                                 134
Swedish                            131
African                            128
Anglican Church                    126
Community                          126
He                                 125
Is                                 125
Ki                                 124
Ir                                 123
Tardo                              123
Wananchi                           122
Snv                                122
Roman Catholic                     121
Wua                                121
Unice                              119
Bsf                                117
Tassaf                             116
Co                                 111
Dfid                               110
Lamp                               110
Concern                            108
Muwsa                              107
Villagers                          106
Village Council                    105
Ru                                 105
Halmashauri Ya Wilaya Sikonge      102
Germany                            101
Hsw                                101
Twe                                 97
Idc                                 92
Tanza                               88
Missi                               87
Undp                                86
Mdrdp                               86
H                                   86
Aict                                85
Gtz                                 84
Japan                               82
Cmsr                                81
Rc Ch                               80
Vwc                                 78
Ndrdp                               78
Fin Water                           72
Kuwait                              72
Lwi                                 72
Cdtf                                70
Caritas                             70
Kkkt Church                         70
Kaemp                               69
Padep                               69
Kibaha Town Council                 68
Marafip                             68
Conce                               68
Water Aid /sema                     68
Cefa                                67
Ncaa                                63
Commu                               62
National Rural                      62
Mkinga  Distric Cou                 62
Losaa-kia Water Supply              62
Md                                  61
Sabemo                              59
Irish Ai                            59
Plan International                  57
Twesa                               56
Kirde                               54
Tlc                                 54
St                                  54
Idara Ya Maji                       54
Gen                                 54
Grumeti                             53
Solidarm                            53
Kilindi District Co                 53
Finida German Tanzania Govt         53
Wfp                                 52
Cocen                               52
Ta                                  51
China Government                    51
Tanapa                              51
Dwe/norad                           50
Sema                                50
Tabora Municipal Council            49
European Union                      48
Solidame                            48
Ridep                               47
Dwssp                               47
Devon Aid Korogwe                   46
Acra                                46
Miziriol                            46
Dads                                46
Shawasa                             45
Red Cross                           45
Redep                               44
Abasia                              43
Tz Japan                            43
Giz                                 42
Ms                                  42
Donor                               41
Cafod                               41
Serikali                            41
Tdft                                41
Un                                  40
Soda                                40
Tredep                              40
Ka                                  39
Jbg                                 38
Songea District Council             38
Kuwasa                              38
Dasip                               37
Fathe                               37
Urt                                 36
Kidp                                36
W                                   36
African Development Bank            35
Mbiuwasa                            35
Songea Municipal Counci             35
Islamic Found                       35
Watu Wa Ujerumani                   35
Water User As                       34
Si                                  34
Finn Water                          33
Ics                                 33
Holland                             33
Oikos E.Africa/european Union       33
Aar                                 33
Ilo                                 33
Kiuma                               32
Peters                              32
Dhv\norp                            32
Tuwasa                              32
Biore                               31
The Desk And Chair Foundat          31
Kanisa Katoliki Lolovoni            31
Cspd                                30
Churc                               30
Jika                                30
Po                                  30
Ga                                  30
Swiss If                            30
Peter Tesha                         30
Kalta                               30
Happy Watoto Foundation             30
Cg                                  30
Il                                  29
Finwater                            29
Cocern                              29
World Vision/adra                   29
Kidep                               29
Sida                                28
Save The Rain Usa                   28
Ereto                               28
Undp/ilo                            28
Water Aid/sema                      28
Not Known                           27
Ifad                                27
Lips                                27
Kanisa La Menonite                  27
Dw                                  27
Hw/rc                               27
Village Government                  27
Partage                             27
I Wash                              27
Halmashauri                         27
Songas                              27
Quwkwin                             26
Nethe                               26
Mileniam Project                    26
Plan Internatio                     26
Wwf                                 26
Cdcg                                26
Dadis                               25
Hans                                25
Rc Churc                            25
Hewasa                              25
Tacare                              25
Kilwater                            25
Adp                                 25
Total Land Care                     25
Village                             25
Care International                  24
Bgm                                 24
Rished                              24
Missionaries                        24
Roman Cathoric-same                 24
Tanzakesho                          24
Kalitasi                            24
Sabodo                              23
Wd And Id                           23
Ilct                                23
Cefa-njombe                         23
Cmcr                                23
Rcchurch/cefa                       22
Bank                                22
Mwaya Mn                            22
Luthe                               22
Village Community                   22
Swisland/ Mount Meru Flowers        21
Cipro/government                    21
Killflora                           21
Singida Yetu                        21
Vifafi                              21
Norad /government                   20
Norad/ Kidep                        20
Islamic                             20
Sekei Village Community             20
Msf                                 20
Dct                                 19
Makonde Water Population            19
Peace Cope                          19
Dhv Moro                            19
Rotary Club                         19
Magoma Adp                          19
P                                   19
Kuamu                               19
Sowasa                              19
Efg                                 19
Kadp                                19
Water Board                         19
Maji Mugumu                         19
Tanzania                            18
Eu/acra                             18
Ham                                 18
Dasp                                18
Cct                                 18
Pidp                                18
Mbunge                              18
Asb                                 18
The People Of Japan                 18
Ubalozi Wa Marekani                 18
One Un                              18
Gain                                18
Drdp Ngo                            17
Sdg                                 17
Father Bonifasi                     17
Mdc                                 17
Sumbawanga Munici                   17
Ukiligu                             17
Bahewasa                            17
Msabi                               17
Bened                               17
Tasaf/dmdd                          17
Idydc                               17
Mkuyu                               17
Ruthe                               16
Tado                                16
Msikiti                             16
Isf/government                      16
Pmo                                 16
Finland Government                  16
Rwsp                                16
Tahea                               16
Rdc                                 16
Mi                                  16
Sda                                 16
Lwiji Italy                         16
Livin                               16
Quick Wings                         16
Bruder                              16
Fpct                                15
African Muslim Agency               15
African Relie                       15
Finland                             15
Resolute Mining                     15
Roman Cathoric Same                 15
Elct                                15
A/co Germany                        15
Shule                               15
Us Embassy                          15
Dar Al Ber                          15
Quick Wins                          15
Isingiro Ho                         14
Olgilai Village Community           14
Isf/tacare                          14
Private Owned                       14
Rc Church/centr                     14
Roman Catholic Rulenge Diocese      14
Imf                                 14
Wfp/tnt/usaid                       14
Mamad                               14
Roman Church                        14
Adp Mombo                           14
Sao H                               14
Living Water International          14
Dassip                              14
Maxavella                           13
Aic                                 13
Bulyahunlu Gold Mine                13
The Isla                            13
Jeica                               13
Msf/tacare                          13
Halmashauri Ya Manispa Tabora       13
Qwiqwi                              13
Tassaf I                            13
Rada                                13
Franc                               13
Undp/aict                           13
Aco/germany                         13
Mosque                              13
Lgcdg                               13
Rural Water Supply And Sanita       13
Ba As                               13
Village Council/ Haydom Luther      13
Water Project Mbawala Chini         13
Benguka                             13
Af                                  12
Mh An                               12
Tridep                              12
National Rural And Hfa              12
Institution                         12
Kinapa                              12
Lowasa                              12
Ai                                  12
Secondary                           12
Lutheran Church                     12
Canada                              12
Oxfam Gb                            12
Qwickwin                            12
Rips                                12
Kwikwiz                             12
Prf                                 12
Lifetime                            12
Government/ Community               11
Wfp/tnt                             11
Finidagermantanzania Govt           11
Dak                                 11
Germany Misionary                   11
Idea                                11
Unicef/central                      11
Kkkt-dioces Ya Pare                 10
Muslims                             10
De                                  10
Auwasa                              10
Chamavita                           10
Tasafu                              10
Tag                                 10
Millenium                           10
Dhv/gove                            10
Kmcl                                10
Belgian Government                  10
Sijm                                10
Snv Ltd                             10
Suwasa                              10
Nado                                10
Kanisa                               9
Kadres Ngo                           9
Regional Water Engineer Arusha       9
Mem                                  9
Kingupira S                          9
Desk And Chair Foundation            9
Government/ World Bank               9
Williamson Diamond Ltd               9
People Of Japan                      9
Cobashec                             9
Aimgold                              9
Koica                                9
Pci                                  9
Hortanzia                            9
Action Contre La Faim                9
Women For Partnership                9
Mzinga A                             9
Holla                                9
Ikela Wa                             9
W.D & I.                             9
Council                              9
Tassaf Ii                            9
Healt                                9
Water User Group                     9
Bffs                                 9
Serikali Ya Kijiji                   9
Lottery Club                         8
British Colonial Government          8
Ebaha                                8
I.E.C                                8
Do                                   8
Tltc                                 8
Camavita                             8
Member Of Parliament                 8
Duwas                                8
Government /tassaf                   8
Moroil                               8
Roman Cathoric -kilomeni             8
Olumuro                              8
Rundu Man                            8
D                                    8
Action Aid                           8
Kilomber                             8
France                               8
Mamlaka Ya Maji Ngara                8
Br                                   8
Nk                                   8
Professor Ben Ohio University        8
Milenia                              8
Morovian Church                      8
Sengerema District Council           8
Halmashaur                           8
Angrikana                            8
Mtuwasa                              8
Africare                             7
Mbozi District Council               7
Unicef/ Csp                          7
Kanisa Katoliki                      7
Parastatal                           7
Abd                                  7
Village Govt                         7
Local                                7
Mws                                  7
Kyela Council                        7
School                               7
Bs                                   7
Sauwasa                              7
Baric                                7
Menon                                7
El                                   7
Cipro/care/tcrs                      7
Summit For Water                     7
Hapa                                 7
Sangea District Council              7
Lawate Fuka Water Suppl              7
Baptist Church                       7
Rwsssp                               7
Secondary Schoo                      6
Mac                                  6
Kimkuma                              6
Jimbo Fund                           6
World Vision/ Kkkt                   6
Jeshi La Wokovu                      6
Mboma                                6
Moslem Foundation                    6
Mzungu Paul                          6
Gaica                                6
Total Landcare                       6
U.S.A                                6
Robert Loyal                         6
Mheza Distric Counc                  6
Semaki K                             6
Makonde                              6
Pataji                               6
Adf                                  6
In                                   6
Concern /govern                      6
Quick                                6
Wate Aid/sema                        6
Re                                   6
African Development Foundation       6
Rwssp/wsdp                           6
Sanje Wa                             6
Islam                                6
Filo                                 6

Se puede clasificar en estos grupos:
**Gobierno de Tanzania**
**Organizaciones Religiosas**
**Ayudas internacional/ONGs**
**Paises extranjeros**
**Privados/Locales**
**Desconocido**
**Otros**

### Instaler

In [28]:
print(df_fase2['installer'].value_counts().to_string())

installer
DWE                               17402
Unknown                            3658
Government                         1825
RWE                                1206
Commu                              1060
DANIDA                             1050
KKKT                                898
Hesawa                              840
0                                   777
TCRS                                707
Central government                  622
CES                                 610
Community                           553
DANID                               552
District Council                    551
HESAWA                              539
World vision                        408
LGA                                 408
WEDECO                              397
TASAF                               396
District council                    392
Gover                               383
AMREF                               329
TWESA                               316
WU                                  301
Dmdd                                287
ACRA                                278
World Vision                        270
SEMA                                249
DW                                  246
OXFAM                               234
Da                                  224
UNICEF                              222
Idara ya maji                       222
Gove                                222
Sengerema Water Department          214
Kiliwater                           210
FinW                                208
NORAD                               208
DH                                  202
Villagers                           199
DWSP                                192
Distri                              181
Lawatefuka water sup                180
Magadini-Makiwaru wa                175
RC                                  174
FW                                  173
KKKT _ Konde and DWE                166
Centr                               162
WVT                                 158
MWE                                 157
Handeni Trunk Main(                 156
Is                                  154
Norad                               152
Fini Water                          149
RWSSP                               149
SHIPO                               147
Private                             143
Kuwait                              142
JAICA                               141
Central govt                        138
Artisan                             135
ISF                                 135
Fini water                          133
GOVER                               128
DDCA                                126
HE                                  125
RC CHURCH                           125
Tardo                               123
World                               121
Mission                             121
Ir                                  119
wananchi                            119
Consulting Engineer                 116
Amref                               114
JICA                                113
TWE                                 111
Central Government                  110
MUWSA                               107
DED                                 105
WATER AID                           103
FINI WATER                          103
Halmashauri ya wilaya sikonge       102
Wizara ya maji                      100
HSW                                 100
Unisef                               98
Jaica                                98
Ki                                   97
Go                                   97
OXFARM                               96
World Bank                           95
Roman                                94
Angli                                92
VWC                                  91
District water department            89
DMDD                                 89
Missi                                87
Shipo                                86
H                                    86
DA                                   84
AICT                                 84
MDRDP                                84
Water board                          81
Adra                                 80
Oikos E .Africa                      80
District Water Department            78
Region water Department              77
CEFA                                 75
RC Church                            75
Chamavita                            75
Danid                                72
Water                                71
LWI                                  71
Wa                                   69
KKKT CHURCH                          69
GOVERNMENT                           66
Villa                                65
MTN                                  65
DAWASCO                              64
TASSAF                               64
GTZ                                  63
Finwater                             62
Losaa-Kia water supp                 62
Adra/Community                       60
LVIA                                 60
Wachina                              60
FIN WATER                            59
Village Council                      58
NCAA                                 57
Adra /Community                      55
TLC                                  55
GEN                                  55
Co                                   55
ADRA                                 55
RDC                                  55
DHV                                  54
Priva                                54
Communit                             54
St                                   54
Pr                                   53
RWE/DWE                              52
RC Ch                                52
wanan                                52
Local te                             52
CDTF                                 50
Water Aid                            48
KUWAIT                               47
Local  technician                    47
WORLD BANK                           47
Plan Internationa                    46
MLADE                                46
District water depar                 46
Miziriol                             46
KA                                   46
SHAWASA                              45
Local                                45
SOLIDAME                             45
Water Aid /sema                      44
TDFT                                 42
VILLAGE COUNCIL                      42
Ga                                   42
CBHCC                                41
JANDU PLUMBER CO                     41
MWE &                                40
GRUMETI                              39
KILI WATER                           38
KUWASA                               38
JBG                                  37
SHY BUILDERS                         37
KIDP                                 36
RED CROSS                            36
MBIUWASA                             35
BSF                                  35
HAPA SINGIDA                         34
Ch                                   34
FINN WATER                           33
Tanzania Government                  33
MUWASA                               33
SI                                   33
KKT                                  33
KIUMA                                32
TUWASA                               32
Wananchi                             32
VTECOS                               32
LOCAL CONTRACT                       31
WATERAID                             31
HOLLAND                              31
The desk and chair foundat           31
Msabi                                31
TANAPA                               31
Accra                                30
Kokeni                               30
KAEMP                                30
Kalta                                30
WB                                   30
Happy watoto foundation              30
CCEC                                 29
FinWater                             29
Po                                   29
Swiss If                             29
Do                                   29
ABASIA                               29
PADEP                                29
Gwasco L                             28
Rhobi                                28
Jica                                 28
UN                                   27
ERETO                                27
Local technician                     27
CJEJOW CONSTRUCTION                  27
HW/RC                                27
COCANE                               27
GOVERN                               27
BESADA                               26
Active MKM                           26
WD and ID                            26
IFAD                                 25
Hans                                 25
Af                                   25
ICS                                  25
JUIN CO                              25
TAN PLANT LTD                        25
Kilwater                             25
TAWASA                               25
Serikali                             25
Individuals                          24
CONS                                 24
GEOTAN                               24
JIKA                                 24
PET                                  24
CMSR                                 24
Mileniam project                     24
not known                            24
Kalitasi                             24
RIDEP                                24
Wo                                   24
Ce                                   23
KYASHA ENTERPR                       23
MTUWASA                              23
ILCT                                 23
WWF                                  23
Total land care                      23
Korogwe water works                  23
Halmashauri                          23
VIFAFI                               23
NYAKILANGANI CO                      23
TREDEP                               23
Sabodo                               22
Care international                   22
TA                                   22
Ndanda missions                      22
Fathe                                22
Hydrotec                             22
MARAFIP                              22
CONCERN                              22
Cosmo                                22
RCchurch/CEFA                        21
CIPRO/Government                     21
NORA                                 21
BGM                                  21
Save the rain USA                    21
Consuting Engineer                   21
Jicks                                21
W/                                   21
Islamic                              20
Sekei village community              20
WORLD VISION                         20
SINGIDA YETU                         20
KADP                                 20
UDC/Sema                             20
Makonde water population             19
ADP                                  19
Maswi company                        19
Kuamu                                19
Orien                                19
KIM KIM CONSTRUCTION                 19
SOWASA                               19
MA                                   19
CG                                   19
private                              19
P                                    18
Mi                                   18
EFG                                  18
IDYDC                                18
Concern                              18
JANDU PLUMBER  CO                    18
Not known                            17
Plan Int                             17
Tanz                                 17
QUWKWIN                              17
Chur                                 17
Sumbaw                               17
Adra/ Community                      17
UKILIG                               17
Mbunge                               17
DADS                                 17
TASAF/DMDD                           17
CITIZEN ENGINE                       17
central government                   17
Mkuyu                                17
MAJI MUGUMU                          17
Ruthe                                16
ISF/Government                       16
Finland Government                   16
SDA                                  16
BRUDER                               16
WFP                                  15
Regional Water                       15
Grobal resource alliance             15
TPP TRUSTMOSHI                       15
US Embassy                           15
The I                                15
TAHEA                                15
MSF                                  15
Mackd                                15
Naishu construction co. ltd          15
Village Community                    15
Tasaf                                15
RWE /Community                       15
LIVI                                 15
Ja                                   15
hesawa                               15
Cefa                                 15
Olgilai village community            14
FPCT                                 14
RW                                   14
RC Churc                             14
AD                                   14
RC church/Central Gover              14
Ma                                   14
ADP Busangi                          14
CENTRAL GOVERNMENT                   14
SIA Ltd                              14
Roman Church                         14
Water Aid/sema                       14
Sao                                  14
Living water international           14
District Counci                      13
Phase                                13
Mw                                   13
Kiliflora                            13
The Isla                             13
Rotary club                          13
MSF/TACARE                           13
Inter                                13
DWE}                                 13
WSDP                                 13
MINISTRY OF WATER                    13
ISF/TACARE                           13
RWSP                                 13
Village community                    13
Mviwa                                13
MAMAD                                13
WOULD BANK                           13
villagers                            13
Pet Corporation Ltd                  13
QWICKWIN                             13
SAXON                                13
Canop                                13
Water Project Mbawala chini          13
VILLAG                               13
Mpang                                13
Nandra Construction                  13
BENGUKA                              13
HAM                                  12
DWR                                  12
Jeica                                12
World Vission                        12
Halmashauri ya manispa tabora        12
Vill                                 12
W                                    12
Consultant                           12
UNHCR                                12
Water Aid/Sema                       12
Goldstar                             12
DISTRICT COUNCIL                     12
Cosmos Engineering                   12
Killflora/ Community                 12
Canada na Tanzania                   12
RC C                                 12
Unicef                               12
PRF                                  12
DALDO                                12
Karugendo                            11
PIDP                                 11
ML appro                             11
World bank                           11
DAK                                  11
Conce                                11
AI                                   11
Mosque                               11
Msikiti                              11
Exaud Msambwa                        11
Consultant Engineer                  11
KKKT-Dioces ya Pare                  10
D                                    10
Nice                                 10
AUWASA                               10
TAG                                  10
LAMP                                 10
CHINA HENAN CONTRACTOR               10
WATER  AID                           10
Gwaseco                              10
KMCL                                 10
Songa                                10
Gain                                 10
SONGAS                               10
secondary                            10
KkKT                                 10
HAPA                                 10
Serikali ya kijiji                   10
Rips                                 10
SIJM                                 10
IDEA                                 10
SULEMAN IDD                          10
Ardhi water well                     10
KWIKWIZ                              10
Mamlaka ya maji ngara                10
RUDEP/                               10
SUWASA                               10
Milenia                              10
AIC                                  10
ATIGH BUILDINGS                      10
Maswi                                10
Dr. Matomola                          9
REGIONAL WATER ENGINEER ARUSHA        9
IDARA                                 9
Victoria                              9
Kilwa company                         9
Ubung                                 9
CCT                                   9
European Union                        9
Kalumbwa                              9
Roman Catholic Rulenge Diocese        9
ACTIVE TANK CO                        9
Kalago enterprises Co.Ltd             9
No                                    9
WILLIAMSON DIAMOND LTD                9
Japan                                 9
Ministry of water engineer            9
Ubalozi wa Marekani                   9
AIMGOLD                               9
Mzinga A                              9
Ikela Wa                              9
AMP contractor                        9
GERMANY MISSIONARY                    9
CARTAS                                9
RUDEP                                 9
Redep                                 9
Healt                                 9
Singida General  Supplies  Ltd        9
MISSION                               9
VILLAGERS                             9
REDESO                                8
Rhoda                                 8
I.E.C                                 8
Killflora /Community                  8
DO                                    8
Bulyahunlu Gold Mine                  8
TLTC                                  8
Action Contre La Faim                 8
DUWAS                                 8
Institution                           8
Contr                                 8
Moroil                                8
PIT COOPERATION  LTD                  8
Roman Cathoric Same                   8
Roman Cathoric -Kilomeni              8
Council                               8
PCI                                   8
Belgiam Government                    8
lutheran church                       8
Village Government                    8
MI                                    8
BR                                    8
WUA                                   8
VILLAGE COUNCIL Orpha                 7
Save the rain                         7
RWE/ Community                        7
DWE/                                  7
COSMOS ENG LTD                        7
SIMBA CO                              7
Village                               7
DCT                                   7
KTA C                                 7
SAXON BUILDING CONTRACTOR             7
MACK DONALD CONTRACTOR                7
COUN                                  7
Village govt                          7
RWE/Community                         7
Konoike                               7
Makonde                               7
Kigoma municipal                      7
MWS                                   7
KONOIKE                               7
Germany                               7
SAUWASA                               7
Rundu man                             7
Concern /government                   7

Se puede clasificar en estos grupos:
**DWE**
**Gobierno y Entidades Públicas**
**Organizaciones Religiosas**
**Ayudas internacional/ONGs**
**Paises extranjeros**
**Privados/Locales**
**Desconocido**
**Otros**

### lga

In [29]:
print(df_fase2['lga'].value_counts().to_string())

lga
Njombe              2503
Arusha Rural        1252
Moshi Rural         1251
Bariadi             1177
Rungwe              1106
Kilosa              1094
Kasulu              1047
Mbozi               1034
Meru                1009
Bagamoyo             997
Singida Rural        995
Kilombero            959
Same                 877
Kibondo              874
Kyela                859
Kahama               836
Kigoma Rural         824
Magu                 824
Maswa                809
Karagwe              771
Mbinga               750
Iringa Rural         728
Serengeti            716
Namtumbo             694
Lushoto              694
Songea Rural         693
Mpanda               679
Mvomero              671
Ngara                669
Ulanga               665
Makete               630
Kwimba               627
Mbarali              626
Hai                  625
Rombo                594
Shinyanga Rural      588
Nzega                575
Ludewa               564
Mkuranga             560
Iramba               544
Masasi               528
Kondoa               523
Sumbawanga Rural     521
Morogoro Rural       521
Mufindi              520
Mwanga               519
Bukombe              514
Babati               511
Ilala                497
Geita                488
Bukoba Rural         487
Mbeya Rural          485
Meatu                468
Rufiji               454
Bunda                438
Siha                 434
Nkasi                428
Tunduru              423
Mtwara Rural         423
Korogwe              412
Biharamulo           403
Muleba               402
Kishapu              399
Musoma Rural         396
Kilwa                392
Lindi Rural          388
Mpwapwa              388
Urambo               382
Manyoni              377
Kongwa               361
Dodoma Urban         358
Kilolo               349
Missungwi            348
Chamwino             347
Ukerewe              341
Uyui                 339
Igunga               338
Muheza               334
Sengerema            331
Karatu               326
Longido              310
Simanjiro            308
Pangani              305
Nachingwea           300
Chunya               298
Mbulu                297
Ruangwa              291
Mkinga               288
Hanang               274
Kibaha               269
Tandahimba           266
Misenyi              260
Handeni              254
Chato                236
Ileje                231
Newala               231
Bahi                 224
Kisarawe             223
Temeke               215
Rorya                210
Tarime               209
Ngorongoro           201
Kiteto               193
Shinyanga Urban      191
Monduli              189
Sumbawanga Urban     180
Singida Urban        177
Sikonge              170
Kilindi              161
Nanyumbu             158
Tabora Urban         155
Liwale               154
Ilemela              142
Mafia                132
Mtwara Urban         124
Tanga                 99
Morogoro Urban        96
Kinondoni             93
Bukoba Urban          88
Songea Urban          80
Moshi Urban           79
Kigoma Urban          71
Arusha Urban          63
Lindi Urban           21
Nyamagana              1

Se puede clasificar en estos grupos:
**Urban**
**Rural**
**Other**

### Ward

In [30]:
print(df_fase2['ward'].value_counts().to_string())

ward
Igosi                      307
Imalinyi                   252
Siha Kati                  232
Mdandu                     231
Nduruma                    217
Kitunda                    203
Mishamo                    203
Msindo                     201
Chalinze                   196
Maji ya Chai               190
Usuka                      187
Ngarenanyuki               172
Chanika                    171
Vikindu                    162
Mtwango                    153
Matola                     145
Zinga/Ikerege              141
Wanging'ombe               139
Maramba                    139
Itete                      137
Magomeni                   135
Kikatiti                   134
Ifakara                    134
Olkokola                   133
Maposeni                   130
Mvomero                    129
Igongolo                   129
Mlangali                   125
Nkoma                      122
Mahongole                  121
Nkungulu                   121
Rujewa                     120
Simbo                      118
Masama Magharibi           116
Mamire                     115
Kiranyi                    115
Lupalilo                   114
Kidatu                     114
Kagongo                    113
Ihanda                     113
Hedaru                     112
Chinamili                  111
Isongole                   109
Siha Mashariki             109
Masama Mashariki           107
Mkongo                     107
Tinde                      106
Yombo                      106
Makuyuni                   106
Kanga                      105
Kimochi                    104
Makwale                    104
Bugarama                   104
Soga                       103
Diongoya                   103
Malindi                    103
Mabwerebwere               102
Mahembe                    101
Kirua Vunjo Kusini          98
Kibaoni                     98
Leguruki                    97
Ilolangulu                  96
Lembeni                     95
Ruhembe                     95
Ruanda                      93
Bungu                       93
Mhunze                      92
Mlangarini                  92
Mang'ula                    91
Kakonko                     90
Mlali                       90
Lumemo                      89
Uwemba                      89
Rusumo                      89
Kifanya                     88
Chimala                     88
Munyegera                   87
Ipande                      87
Magagura                    87
Kenyamonta                  87
Kisesa                      87
Ubaruku                     86
Mbulumbulu                  86
Murufiti                    86
Chanzuru                    86
Ilkiding'a                  86
Matendo                     85
Wino                        85
Mkula                       84
Muzye                       84
Muhinda                     83
Lupembe                     83
Mpuguso                     83
Mapogoro                    83
Kibosho Magharibi           82
Msia                        81
Keni Mengeni                81
Nyimbili                    81
Nkololo                     80
Manyoni                     80
Busole                      80
Ilima                       79
Kimnyaki                    79
Kidodi                      79
Igurusi                     77
Ushirombo                   77
Rungwe Mpya                 77
Oldonyosambu                77
Lugoba                      76
Kirongwe                    76
Machame Uroki               76
Oltroto                     75
Lupata                      75
Mbuyuni                     75
Nyakitonto                  75
Boma la ng'ombe             74
Kiwira                      74
Ipililo                     74
Ruhita                      74
Chakwale                    74
Lupila                      74
Nkwenda                     74
Luegu                       74
Bumera                      74
Samuye                      73
Mwaya                       73
Ulenje                      73
Mwandoya                    73
Pugu                        73
Msata                       73
Kyimo                       73
King'ori                    72
Malinyi                     72
Mbwewe                      72
Somanda                     72
Isandula                    72
Natta                       71
Mkalamo                     71
Lufingo                     71
Busilili                    70
Ilembula                    70
Hembeti                     70
Kihorogota                  70
Rusesa                      70
Mlimba                      70
Rugongowe                   69
Njoro                       69
Lwangwa                     69
Sakasaka                    69
Isansa                      69
Machame Kusini              69
Ushirika                    68
Mpitimbi                    68
Ketumbeine                  68
Mtinko                      68
Machame Kaskazini           68
Kalinzi                     68
Iyula                       67
Ukumbi                      67
Ikolo                       67
Ihanja                      67
Kalangalala                 66
Kibondo Urban               66
Kileo                       66
Namabengo                   66
Mwagi                       66
Nyarubungo                  66
Olmolog                     66
Ikuka                       65
Lutebe                      65
Chala                       65
Utete                       65
Nyamuswa                    65
Namanga                     64
Kassambya                   64
Namanyere                   64
Mpindo                      64
Madilu                      64
Janda                       64
Namajani                    64
Pangani Mashariki           64
Munga'a                     64
Mugumu Urban                64
Qurus                       63
Ilongero                    63
Itaka                       63
Biharamulo Urban            63
Makambako                   63
Myangayanga                 63
Esilalei                    63
Mseke                       62
Salawe                      62
Matema                      62
Lusungo                     62
Ipinda                      62
Kahe                        61
Mang'oto                    61
Nyololo                     61
Lagangabilili               61
Matimira                    61
Buchambi                    61
Katumba                     61
Ikungu                      60
Mshewa                      60
Mwamala                     60
Mamba                       60
Dumila                      60
Ngerengere                  60
Sukuma                      60
Kisanga                     60
Endabash                    60
Kibimba                     60
Kibiti                      59
Shume                       59
Kwai                        59
Mwaniko                     59
Igalula                     59
Kwakoa                      59
Malolo                      59
Machame Mashariki           59
Bujashi                     59
Siha Kaskazini              58
Kiruruma                    58
Msongola                    58
Madibira                    58
Masange                     58
Lulindi                     58
Kisemu                      58
Sanje                       58
Mawengi                     57
Ndalambo                    57
Lukulendi                   57
Mwika Kusini                57
Nambinzo                    57
Mabamba                     57
Mbebe                       57
Usanda                      57
Arusha Chini                57
Ikunguigazi                 57
Busagara                    57
Kiromo                      56
Runazi                      56
Mtimbira                    56
Lufilyo                     56
Image                       56
Bonde la Songwe             56
Ntobeye                     56
Nsimbo                      56
Luduga                      56
Mkigo                       55
Kurua Vunjo Mashariki       55
Marumba                     55
Iwindi                      55
Liuli                       55
Mgombasi                    55
Kihanga                     55
Nyabubinza                  55
Old Moshi Mashariki         55
Mwazye                      55
Msitu wa Tembo              55
Kitagata                    54
Mwembe                      54
Magawa                      54
Kigonsera                   54
Sakwe                       54
Bitale                      54
Sungaji                     54
Iwawa                       54
Mkuranga                    54
Katumbasongwe               53
Rubeho                      53
Kisondela                   53
Mererani                    53
Ibadakuli                   53
Irole                       53
Mahanje                     53
Somangira                   53
Shinghatini                 53
Ikondo                      53
Mbinga Urban                53
Lusewa                      53
Muganza                     53
Utengule Usongwe            53
Nyamatare                   53
Tambani                     52
Oltrumet                    52
Lusahunga                   52
Siuyu                       52
Kirua Vunjo Magharibi       52
Bugoro                      52
Idete                       52
Kilagano                    52
Kolandoto                   52
Kate                        52
Dareda                      52
Nzihi                       52
Saja                        52
Busawe                      52
Gwanumpu                    51
Marangu Mashariki           51
Myovizi                     51
Missungwi                   51
Buterankuzi                 51
Kidegembye                  51
Songoro                     51
Ngana                       51
Loibor Siret                51
Lumuma                      51
Nyang'hwale                 50
Usagara                     50
Mugoma                      50
Didia                       50
Mazinde                     50
Iniho                       50
Pahi                        50
Maboga                      50
Machochwe                   50
Luchili                     50
Makanya                     50
Halungu                     50
Mbalamaziwa                 50
Isanga                      49
Msanzi                      49
Bujonde                     49
Shishiyu                    49
Maligisu                    49
Magoma                      49
Nyigogo                     49
Rulenge                     49
Kitanda                     49
Kikunde                     49
Itaba                       49
Kaisho                      48
Wangama                     48
Isingiro                    48
Ukune                       48
Kitirima Kingachi           48
Ruvu                        48
Mtumba                      48
Mkoma                       48
Matai                       48
Njombe Urban                48
Ngorongo                    48
Nyaishozi                   47
Kalenge                     47
Kilindoni                   47
Doma                        47
Kindi                       47
Mgambo                      47
Kitongo Sima                47
Dabil                       47
Kipatimu                    47
Kandaga                     47
Mwena                       47
Kiroka                      46
Kirangare                   46
Kasamwa                     46
Kibara                      46
Pandambili                  46
Pemba Mnazi                 46
Ifunda                      46
Mchombe                     46
Nshamba                     46
Kisangura                   46
Kinyeto                     46
Songambele                  46
Shimbi                      46
Kandete                     46
Kihagara                    46
Nkoaranga                   46
Sapiwi                      46
Igunga                      46
Izimbya                     45
Kyela Urban                 45
Neruma                      45
Akheri                      45
Nkumba                      45
Nyandekwa                   45
Dakama                      45
Mbuga                       45
Ngimu                       45
Sunga                       45
Mogitu                      45
Kisegese                    45
Kulimi                      45
Tingi                       45
Kasanda                     45
Nyamilama                   45
Lumuli                      45
Idodi                       45
Same Urban                  45
Mlowa                       45
Lupanga                     44
Nduguti                     44
Mondo                       44
Igale                       44
Moivo                       44
Gumbiro                     44
Usangule                    44
Ntuntu                      44
Maore                       44
Nyabusozi                   44
Puma                        44
Moshono                     44
Ngudu                       44
Mbogwe                      44
Kadoto                      44
Suma                        44
Mtama                       44
Ndogosi                     44
Munzenze                    43
Ipepo                       43
Uru Kusini Mawela           43
Visiga                      43
Chiugutwa                   43
Mikumi                      43
Ikama                       43
Masama Kusini               43
Kitahana                    43
Mwamgongo                   42
Bunamhala                   42
Suji                        42
Mukituntu                   42
Ligera                      42
Ulaya                       42
Kilosa                      42
Inyonga                     42
Ngongwa                     42
Lugulu                      42
Binagi                      42
Igowole                     42
Kabanga                     42
Kilema Kusini               42
Bukiriro                    42
Sokoni II                   42
Mtenga                      42
Mcharo                      42
Lugarawa                    42
Chela                       42
Vuga                        42
Utengule Usangu             41
Kebanchabancha              41
Sikonge                     41
Uvinza                      41
Mwandiga                    41
Mamba Kusini                41
Isagehe                     41
Mzenga                      41
Mpunze                      41
Mavanga                     41
Melela                      41
Shambarai                   41
Dongobesh                   41
Lingeka                     41
Sepuko                      41
Ubetu Kahe                  41
Ngonga                      41
Katerero                    41
Kinjumbi                    41
Kabwe                       41
Chamkoroma                  41
Kiberege                    40
Kirando                     40
Mshewe                      40
Miono                       40
Kyerwa                      40
Katoro                      40
Malenga Makali              40
Magugu                      40
Kashishi                    40
Kibakwe                     40
Bulungwa                    40
Iragua                      40
Ilunda                      40
Matamba                     40
Ilonga                      40
Muhunga                     40
Mtii                        40
Kisiwani                    39
Masumbwe                    39
Hombolo                     39
Muhange                     39
Komuge                      39
Mandawa                     39
Mahurunga                   39
Lupiro                      39
Mji Mwema                   39
Makuro                      39
Mbezi                       39
Ikhawoda                    39
Chumo                       39
Kahe Mashariki              39
Mkuyuni                     39
Ndumbwe                     39
Mwamapalala                 39
Msowero                     39
Lalago                      39
Nyakato                     39
Mengwe Manda                38
Merya                       38
Nyamnyusi                   38
Nyamigogo                   38
Miangalua                   38
Magara                      38
Mbangala                    38
Kigongo                     38
Inyala                      38
Mwendakulima                38
Mtapenda                    38
Minepa                      38
Mvuha                       38
Kongolo                     38
Murutunguru                 38
Nyambiti                    38
Chiwezi                     38
Kazazi                      38
Igamba                      38
Kharumwa                    38
Murusagamba                 38
Mwang'halanga               38
Nkoanrua                    37
Ndola                       37
Itwangi                     37
Chunyu                      37
Bwawani                     37
Nyakahura                   37
Mahege                      37
Ufukoni                     37
Kihurio                     37
Nyakabindi                  37
Mtibwa                      37
Mahida Holili               37
Luponde                     37
Kasoli                      37
Igalukilo                   37
Iguguno                     37
Mpunguzi                    37
Kibondo                     37
Ilemela                     37
Masama Rundugai             37
Segese                      37
Tanga                       37
Ibiri                       37
Kinang'weli                 37
Kighare                     37
Mundindi                    36
Bunyambo                    36
Mzumbe                      36
Mtowisa                     36
Choma                       36
USA River                   36
Chitete                     36
Rubale                      36
Iyogela                     36
Kishapu                     36
Shelui                      36
Ipala                       36
Nanjara Reha                36
Nyamhula                    36
Ndungu                      36
Mambali                     36
Lusanga                     36
Kabasa                      36
Daluni                      36
Butimba                     36
Kaselya                     36
Malampaka                   36
Kaibanja                    35
Mandewa                     35
Zagayu                      35
Siha Magharibi              35
Budekwa                     35
Ring'wani                   35
Muungano                    35
Ilolo Mpya                  35
Magubike                    35
Ruiwa                       35
Mombo                       35
Kilimatinde                 35
Kirwa Keni                  35
Ughandi                     35
Unyamikumbi                 35
Kisuke                      35
Mwadobana                   35
Nyamtukuza                  35
Kimamba A                   35
Ukwama                      35
Kumsenga                    35
Mwaseni                     35
Maretadu                    35
Igurwa                      35
Berega                      35
Kitere                      34
Tumbi                       34
Badi                        34
Ikindwa                     34
Mgori                       34
Lubugo                      34
Sejeli                      34
Masela                      34
Kanazi                      34
Orkesumet                   34
Bulongwa                    34
Bendera                     34
Kisarawe II                 34
Longido                     34
Kisawasawa                  34
Luana                       34
Mnazi                       34
Engarenaibor                34
Measkron                    33
Kyaka                       33
Isalavanu                   33
Chikuyu                     33
Okoani Kibosho              33
Endasak                     33
Nanjota                     33
Isange                      33
Msisi                       33
Mkamba                      33
Nanga                       33
Butiama                     33
Kisongo                     33
Sumve                       33
Chabutwa                    33
Hungumalwa                  33
Pito                        33
Songwa                      33
Busangi                     33
Wotta                       33
Misezero                    33
Zongomera                   33
Bangata                     33
Bwakila Chini               33
Bwiregi                     33
Ukenyenge                   33
Segala                      33
Kasela                      33
Ulanda                      33
Goba                        33
Runzewe                     33
Mayanga                     33
Nanyumbu                    32
Itetemia                    32
Mkowe                       32

Al no ver nada en comun y no poder clasificarla la eliminamos

### Scheme_management

In [31]:
print(df_fase2['scheme_management'].value_counts().to_string())

scheme_management
VWC                 36793
WUG                  5206
Other                4644
Water authority      3153
WUA                  2883
Water Board          2748
Parastatal           1680
Private operator     1063
Company              1061
SWC                    97
Trust                  72

Se puede clasificar en estos grupos:
**Comunidades**
**Gestión Pública**
**Gestión Comercial/Privada**
**Otros**

### extraction_type_class

In [32]:
print(df_fase2['extraction_type_class'].value_counts().to_string())

extraction_type_class
gravity         26780
handpump        16456
other            6430
submersible      6179
motorpump        2987
rope pump         451
wind-powered      117

No se va a tocar

### management_group

In [33]:
print(df_fase2['management_group'].value_counts().to_string())

management_group
user-group    52490
commercial     3638
parastatal     1768
other           943
unknown         561

No se va a tocar

### payment

In [34]:
print(df_fase2['payment'].value_counts().to_string())

payment
never pay                25348
pay per bucket            8985
pay monthly               8300
unknown                   8157
pay when scheme fails     3914
pay annually              3642
other                     1054

No se va a tocar

### quality_group

In [35]:
print(df_fase2['quality_group'].value_counts().to_string())

quality_group
good        50818
salty        5195
unknown      1876
milky         804
colored       490
fluoride      217

No se va a tocar

### quantity

In [36]:
print(df_fase2['quantity'].value_counts().to_string())

quantity
enough          33186
insufficient    15129
dry              6246
seasonal         4050
unknown           789

No se va a tocar

### source_type

In [37]:
print(df_fase2['source_type'].value_counts().to_string())

source_type
spring                  17021
shallow well            16824
borehole                11949
river/lake              10377
rainwater harvesting     2295
dam                       656
other                     278

No se va a tocar

### waterpoint_type_group

In [38]:
print(df_fase2['waterpoint_type_group'].value_counts().to_string())

waterpoint_type_group
communal standpipe    34625
hand pump             17488
other                  6380
improved spring         784
cattle trough           116
dam                       7

No se va a tocar

## Resumen acciones Cardinalidad
**Campos reducidos**: Funder, Instaler, Lga, Scheme_management.
**Campos eliminados**: Ward, wpt_name

In [39]:

def Cardinalidad(df):

    df_agrupado = df.copy()

    # 1. DICCIONARIOS DE AGRUPACIÓN (Funciones internas)
    def agrupar_funder(nombre):
        if pd.isna(nombre): return 'Unknown'
        name = str(nombre).lower()
        if name in ['0', 'unknown', 'not known', 'none', '-']: return 'Unknown'
        if any(w in name for w in ['gov', 'ministry', 'council', 'lga', 'serikali', 'municipal', 'district', 'halmashauri', 'water board']): return 'Government'
        if any(w in name for w in ['church', 'catholic', 'roman', 'rc ', 'mission', 'diocese', 'kkkt', 'mosque', 'islam', 'kanisa', 'baptist', 'anglican', 'pentecost']): return 'Religious'
        if any(w in name for w in ['unicef', 'unice', 'world bank', 'w.b', 'w0rld', 'danida', 'vision', 'tasaf', 'oxfam', 'wateraid', 'hesawa', 'rwssp', 'amref', 'dwsp', 'tcrs', 'care', 'fund', 'red cross']): return 'International_NGO'
        if any(w in name for w in ['germany', 'japan', 'netherlands', 'nethalan', 'holland', 'china', 'usaid', 'finland', 'swedish', 'italy', 'british', 'belgian', 'kuwait', 'france']): return 'Foreign_Government'
        return 'Private_Local_Other'

    def agrupar_installer(nombre):
        if pd.isna(nombre): return 'Unknown'
        name = str(nombre).lower()
        if name in ['0', 'unknown', 'not known', 'none', '-']: return 'Unknown'
        if any(w in name for w in ['dwe', 'rwe', 'mwe', 'gov', 'ministry', 'council', 'lga', 'serikali', 'municipal', 'district', 'halmashauri', 'water board', 'idara', 'wizara', 'department']): return 'Government'
        if any(w in name for w in ['church', 'catholic', 'roman', 'rc ', 'mission', 'diocese', 'kkkt', 'mosque', 'islam', 'kanisa', 'baptist', 'anglican', 'pentecost', 'kkt']) or name == 'rc': return 'Religious'
        if any(w in name for w in ['unicef', 'unice', 'world bank', 'w.b', 'danida', 'vision', 'tasaf', 'oxfam', 'wateraid', 'hesawa', 'rwssp', 'amref', 'dwsp', 'tcrs', 'care', 'fund', 'red cross', 'twesa', 'acra']): return 'International_NGO'
        if any(w in name for w in ['germany', 'japan', 'netherlands', 'holland', 'china', 'usaid', 'finland', 'swedish', 'italy', 'british', 'belgian', 'kuwait', 'france', 'norad', 'jica', 'koica', 'wachina']): return 'Foreign_Government'
        return 'Private_Local_Other'

    def agrupar_scheme(scheme):
        if pd.isna(scheme): return 'Other'
        scheme = str(scheme)
        if scheme in ['VWC', 'WUG', 'WUA', 'SWC']: return 'Community'
        elif scheme in ['Water authority', 'Water Board', 'Parastatal']: return 'Government'
        elif scheme in ['Company', 'Private operator', 'Trust']: return 'Private'
        else: return 'Other'

    # 2. APLICAR LAS AGRUPACIONES AL DATAFRAME
    
    # TCampos:
    df_agrupado['funder_grouped'] = df_agrupado['funder'].apply(agrupar_funder)
    df_agrupado['installer_grouped'] = df_agrupado['installer'].apply(agrupar_installer)
    df_agrupado['scheme_grouped'] = df_agrupado['scheme_management'].apply(agrupar_scheme)

    # LGA (Rural vs Urbano)
    lga_str = df_agrupado['lga'].astype(str).str.lower()
    df_agrupado['lga_type'] = np.where(lga_str.str.contains('urban'), 'Urban',
                              np.where(lga_str.str.contains('rural'), 'Rural', 'Other'))

    columnas_a_borrar = ['funder', 'installer', 'scheme_management', 'lga', 'ward', 'wpt_name']
    df_agrupado = df_agrupado.drop(columns=columnas_a_borrar)
    

    return df_agrupado

In [40]:
df_fase3 = Cardinalidad(df_fase2)

In [41]:
df_fase3.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   amount_tsh             59400 non-null  float64
 1   date_recorded          59400 non-null  str
 2   gps_height             59400 non-null  int64
 3   longitude              59400 non-null  float64
 4   latitude               59400 non-null  float64
 5   basin                  59400 non-null  str
 6   region                 59400 non-null  str
 7   population             59400 non-null  float64
 8   public_meeting         59400 non-null  object
 9   permit                 59400 non-null  object
 10  construction_year      59400 non-null  float64
 11  extraction_type_class  59400 non-null  str
 12  management_group       59400 non-null  str
 13  payment                59400 non-null  str
 14  quality_group          59400 non-null  str
 15  quantity               59400 non-null  str
 16  source_type            59400 non-null  str
 17  waterpoint_type_group  59400 non-null  str
 18  has_amount_tsh         59400 non-null  int64
 19  has_construction_year  59400 non-null  int64
 20  has_population         59400 non-null  int64
dtypes: float64(5), int64(4), object(2), str(10)
memory usage: 14.6+ MB

In [42]:
df_fase3.nunique()

amount_tsh                  98
date_recorded              356
gps_height                2428
longitude                57515
latitude                 57517
basin                        9
region                      21
population                1048
public_meeting               2
permit                       2
construction_year           54
extraction_type_class        7
management_group             5
payment                      7
quality_group                6
quantity                     5
source_type                  7
waterpoint_type_group        6
has_amount_tsh               2
has_construction_year        2
has_population               2
dtype: int64

# Conversión a numérica

Primero se va a empezar transformando los float64 a **int64** que se puedan hacer. Tabién transformar date_recorded dejando solo el año

In [43]:
def transformacion_numeros(df):

    df_clean = df.copy()

    columnas_a_entero = ['population', 'construction_year']
    
    for col in columnas_a_entero:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype('int64')
            
    if 'date_recorded' in df_clean.columns:
        df_clean['date_recorded'] = pd.to_datetime(df_clean['date_recorded'])
        
        df_clean['year_recorded'] = df_clean['date_recorded'].dt.year.astype('int64')
        
        df_clean = df_clean.drop(columns=['date_recorded'])

    return df_clean

In [44]:
df_fase4 = transformacion_numeros(df_fase3)

Ahora se aplica **One_Hot_Encoding** a:

In [45]:
def OneHot_Encoding(df):

    df_clean = df.copy()

    columnas_para_ohe = [
        'basin', 'region', 'public_meeting', 'permit',
        'extraction_type_class', 'management_group', 'payment', 
        'quality_group', 'quantity', 'source_type', 'waterpoint_type_group',
        'funder_grouped', 'installer_grouped', 'scheme_grouped', 'lga_type'
    ]

    cols_ohe_existentes = [col for col in columnas_para_ohe if col in df_clean.columns]
    df_clean = pd.get_dummies(df_clean, columns=cols_ohe_existentes, drop_first=True, dtype=int)

    return df_clean

In [46]:
df_fase5 = OneHot_Encoding(df_fase4)

In [47]:
df_fase5.dtypes

amount_tsh                                  float64
gps_height                                    int64
longitude                                   float64
latitude                                    float64
population                                    int64
                                             ...
waterpoint_type_group_communal standpipe      int64
waterpoint_type_group_dam                     int64
waterpoint_type_group_hand pump               int64
waterpoint_type_group_improved spring         int64
waterpoint_type_group_other                   int64
Length: 76, dtype: object

In [48]:
df_fase5.columns

Index(['amount_tsh', 'gps_height', 'longitude', 'latitude', 'population',
       'construction_year', 'has_amount_tsh', 'has_construction_year',
       'has_population', 'year_recorded', 'basin_Lake Nyasa',
       'basin_Lake Rukwa', 'basin_Lake Tanganyika', 'basin_Lake Victoria',
       'basin_Pangani', 'basin_Rufiji', 'basin_Ruvuma / Southern Coast',
       'basin_Wami / Ruvu', 'region_Dar es Salaam', 'region_Dodoma',
       'region_Iringa', 'region_Kagera', 'region_Kigoma', 'region_Kilimanjaro',
       'region_Lindi', 'region_Manyara', 'region_Mara', 'region_Mbeya',
       'region_Morogoro', 'region_Mtwara', 'region_Mwanza', 'region_Pwani',
       'region_Rukwa', 'region_Ruvuma', 'region_Shinyanga', 'region_Singida',
       'region_Tabora', 'region_Tanga', 'public_meeting_True', 'permit_True',
       'extraction_type_class_handpump', 'extraction_type_class_motorpump',
       'extraction_type_class_other', 'extraction_type_class_rope pump',
       'extraction_type_class_submersible',
       'extraction_type_class_wind-powered', 'management_group_other',
       'management_group_parastatal', 'management_group_unknown',
       'management_group_user-group', 'payment_other', 'payment_pay annually',
       'payment_pay monthly', 'payment_pay per bucket',
       'payment_pay when scheme fails', 'payment_unknown',
       'quality_group_fluoride', 'quality_group_good', 'quality_group_milky',
       'quality_group_salty', 'quality_group_unknown', 'quantity_enough',
       'quantity_insufficient', 'quantity_seasonal', 'quantity_unknown',
       'source_type_dam', 'source_type_other',
       'source_type_rainwater harvesting', 'source_type_river/lake',
       'source_type_shallow well', 'source_type_spring',
       'waterpoint_type_group_communal standpipe', 'waterpoint_type_group_dam',
       'waterpoint_type_group_hand pump',
       'waterpoint_type_group_improved spring', 'waterpoint_type_group_other'],
      dtype='str')

Meter las respuestas

In [49]:
df_etiquetas=pd.read_csv('TrainingSetLabels.csv')

In [50]:
df_etiquetas.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            59400 non-null  int64
 1   status_group  59400 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.6 MB

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df_fase5,
    df_etiquetas['status_group'],
    test_size=0.2,
    random_state=42,
    stratify=df_etiquetas['status_group'])

In [52]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [53]:
y_pred = model.predict(X_test)

In [54]:
y_pred

array(['non functional', 'functional', 'functional', ..., 'functional',
       'non functional', 'non functional'], shape=(11880,), dtype=object)

In [55]:
y_test

3290         functional
47666        functional
2538         functional
53117    non functional
51817    non functional
              ...
9006     non functional
20942    non functional
29031    non functional
3493     non functional
257      non functional
Name: status_group, Length: 11880, dtype: str

In [56]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                         precision    recall  f1-score   support

             functional       0.81      0.87      0.84      6452
functional needs repair       0.49      0.32      0.39       863
         non functional       0.83      0.79      0.81      4565

               accuracy                           0.80     11880
              macro avg       0.71      0.66      0.68     11880
           weighted avg       0.79      0.80      0.80     11880

Aunque haya salido unos buenos resultados los pozos funcionales que necesitan reparar han acertado menos de la mitad. Vamos a crearlo otra vez pero pidiendo que plante el triple de arboles, y que preste atención a los pozos que necesitán reparación.

In [58]:
modelo_mejorado = RandomForestClassifier(
    n_estimators=300, 
    random_state=42, 
    class_weight='balanced'
)
modelo_mejorado.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=300,
                       random_state=42)

In [59]:
y_pred_mejorado = modelo_mejorado.predict(X_test)

In [60]:
print(classification_report(y_test, y_pred_mejorado))

                         precision    recall  f1-score   support

             functional       0.82      0.87      0.84      6452
functional needs repair       0.49      0.36      0.41       863
         non functional       0.83      0.80      0.81      4565

               accuracy                           0.80     11880
              macro avg       0.71      0.67      0.69     11880
           weighted avg       0.80      0.80      0.80     11880

In [62]:
!pip install xgboost

Collecting xgboost

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\fortn\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\fortn\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\fortn\anaconda3\Lib\site-packages)

  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\fortn\anaconda3\lib\site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in c:\users\fortn\anaconda3\lib\site-packages (from xgboost) (1.17.0)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 1.6/101.7 MB 8.8 MB/s eta 0:00:12
   -- ------------------------------------- 7.3/101.7 MB 20.1 MB/s eta 0:00:05
   -- ------------------------------------- 7.6/101.7 MB 15.0 MB/s eta 0:00:07
   --- ------------------------------------ 10.0/101.7 MB 14.5 MB/s eta 0:00:07
   ------ --------------------------------- 15.5/101.7 MB 17.1 MB/s eta 0:00:06
   ------- -------------------------------- 20.2/101.7 MB 16.7 MB/s eta 0:00:05
   ---------- ----------------------------- 25.4/101.7 MB 17.8 MB/s eta 0:00:05
   -------------- ------------------------- 36.4/101.7 MB 22.4 MB/s eta 0:00:03
   ------------------ --------------------- 46.4/101.7 MB 25.4 MB/s eta 0:00:03
   ---------------------- ----------------- 56.9/101.7 MB 27.9 MB/s eta 0:00:02
   -------------------------- ------------- 66.3/101.7 MB 29.4 MB/s eta 0:00:02
   ------------------------------ --------- 77.9/101.7 MB 31.6 MB/s eta 0:00:01
   ---------------------------------- ----- 87.8/101.7 MB 32.8 MB/s eta 0:00:01
   --------------------------------------  100.7/101.7 MB 34.9 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 35.0 MB/s eta 0:00:01
   --------------------------------------  101.4/101.7 MB 35.0 MB/s eta 0:00:01
   --------------------------------------- 101.7/101.7 MB 30.7 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [63]:


from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report


le = LabelEncoder()
y_train_num = le.fit_transform(y_train)
y_test_num = le.transform(y_test)


modelo_xgb = XGBClassifier(
    n_estimators=300,        # Número de árboles en la secuencia
    learning_rate=0.1,       # Velocidad a la que aprende de sus errores
    max_depth=6,             # Profundidad de cada árbol (más complejo que Random Forest)
    random_state=42,
    n_jobs=-1
)


modelo_xgb.fit(X_train, y_train_num)


predicciones_xgb = modelo_xgb.predict(X_test)
precision = accuracy_score(y_test_num, predicciones_xgb)

print("\n" + "="*50)
print(f"🏆 PRECISIÓN (ACCURACY) DE XGBOOST: {precision * 100:.2f}%")
print("="*50 + "\n")

print(classification_report(y_test_num, predicciones_xgb, target_names=le.classes_))

Entrenando XGBoost... 🚀 (Esto es pura potencia de cálculo)

==================================================
🏆 PRECISIÓN (ACCURACY) DE XGBOOST: 79.03%
==================================================

                         precision    recall  f1-score   support

             functional       0.77      0.91      0.84      6452
functional needs repair       0.58      0.21      0.30       863
         non functional       0.84      0.74      0.78      4565

               accuracy                           0.79     11880
              macro avg       0.73      0.62      0.64     11880
           weighted avg       0.78      0.79      0.78     11880

Aunque XGBoost es un modelo más complejo, el **Random Forest** balanceado no solo logró una mejor precisión global (80%), sino que casi duplicó el Recall de la clase crítica (del 21% al 36%).

## Puntuación Concurso: Score 0.8020 id-315591